config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :channels, :groups, :users

  get '/channels/:id/new_message', to: 'messages#new', as: 'new_message'
  post '/channels/:id/new_message', to: 'messages#create'

  root 'channels#index'
end

app/models/access.rb
class Access < ApplicationRecord
  belongs_to :channel
  belongs_to :group
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/channel.rb
class Channel < ApplicationRecord
  has_many :messages, -> { order(created_at: :asc) }, dependent: :destroy

  has_many :accesses
  has_many :groups, through: :accesses
  has_many :users, through: :groups

  validates :name, presence: true, uniqueness: true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :accesses
  has_many :channels, through: :accesses

  validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :channel

  validates :content, presence: true
  validate :user_has_access

  def user_has_access
    unless user.channels.include?(channel)
      errors.add(:user, 'does not have access to this channel')
    end
  end

  def get_user_name
    unless user.nil?
      user.name
    else
      'Unknown User'
    end
  end

  def get_time
    created_at.to_s
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :group
  has_many :accesses, through: :group
  has_many :channels, through: :accesses

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  def index
    @channels = Channel.all
  end

  def show
    @channel = Channel.find(params[:id])
  end

  def new
    @channel = Channel.new
  end

  def create
    @channel = Channel.new(channel_params)
    if @channel.save
      redirect_to channel_path(@channel)
    else
      render 'new'
    end
  end

  def edit
    @channel = Channel.find(params[:id])
  end

  def update
    @channel = Channel.find(params[:id])
    if @channel.update(channel_params)
      redirect_to channel_path(@channel)
    else
      render 'edit'
    end
  end

  def destroy
    @channel = Channel.find(params[:id])
    @channel.destroy
    redirect_to channels_path
  end

  private
    def channel_params
      params.require(:channel).permit(:name)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end

  def show
    @group = Group.find(params[:id])
    @users = @group.users
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to group_path(@group)
    else
      render 'new'
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      render 'edit'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  private
    def group_params
      params.require(:group).permit(:name, channel_ids: [])
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
    @channel = Channel.find(params[:id])
  end

  def create
    @message = Message.new(message_params)
    @channel = Channel.find(params[:id])
    if @message.save
      redirect_to channel_path(@channel)
    else
      render 'new'
    end
  end

  private
    def message_params
      params.require(:message).permit(:content, :user_id, :channel_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  private
    def user_params
      params.require(:user).permit(:name, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/channels/_form.html.erb
<%= render 'shared/errors', container: @channel %>

<%= form_for @channel do |f| %>
  <p>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit submit_msg %>
  </p>
<% end %>

app/views/channels/edit.html.erb
<h1>Edit <%= @channel.name %></h1>

<%= render 'form', submit_msg: 'Save Changes' %>

<p>
  <%= link_to 'Cancel', channel_path(@channel) %>
</p>

app/views/channels/index.html.erb
<h1>Channels Index</h1>

<table>
  <tr><%= link_to 'New Channel', new_channel_path %></tr>
  <% @channels.each do |channel| %>
    <tr>
      <td>
        <%= link_to channel.name, channel_path(channel) %>
      </td>
      <td>
        <%= link_to 'Delete',
            channel_path(channel),
            method: :delete,
            data: { confirm: 'Delete this Channel?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/channels/new.html.erb
<h1>Create a New Channel</h1>

<%= render 'form', submit_msg: 'Create Channel' %>

<p>
  <%= link_to 'Cancel', channels_path %>
</p>

app/views/channels/show.html.erb
<h1>Show <%= @channel.name %></h1>

<p>
  Channel Name: <%= @channel.name %>
</p>
<p>
  Accessed by:
  <table>
    <% @channel.groups.each do |group| %>
      <tr><td>
        <%= link_to group.name, group_path(group) %>
      </td></tr>
    <% end %>
  </table>
</p>

<p>
  Messages:
  <table>
    <tr><%= link_to 'Write a Message', new_message_path(@channel) %></tr>
    <% @channel.messages.each do |message| %>
      <tr><td>
        <p>
          <%= message.get_time %> -- <%= message.get_user_name %>
        </p>
        <p>
          <%= message.content %>
        </p>
      </td></tr>
    <% end %>
  </table>
</p>

<p>
  <%= link_to 'Edit Channel', edit_channel_path(@channel) %>
</p>
<p>
  <%= link_to 'Channel Index', channels_path %>
</p>

app/views/groups/_form.html.erb
<%= render 'shared/errors', container: @group %>

<%= form_for @group do |f| %>
  <p>
    <%= f.label 'Group Name:' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'Has Access To:' %>
    <%= f.collection_check_boxes :channel_ids, Channel.all, :id, :name %>
  </p>
  <p>
    <%= f.submit submit_msg %>
  </p>
<% end %>

app/views/groups/edit.html.erb
<h1>Edit <%= @group.name %></h1>

<%= render 'form', submit_msg: 'Save Changes' %>

<p>
  <%= link_to 'Cancel', group_path(@group) %>
</p>

app/views/groups/index.html.erb
<h1>Groups Index</h1>

<table>
  <tr><%= link_to 'New Group', new_group_path %></tr>
  <% @groups.each do |group| %>
    <tr>
      <td>
        <%= link_to group.name, group_path(group) %>
      </td>
      <td>
        <%= link_to 'Delete',
            group_path(group),
            method: :delete,
            data: { confirm: 'Delete this Group and all its Users?' } %>
      </td>
    </tr>
  <% end %>
</table>

app/views/groups/new.html.erb
<h1>Create a New Group</h1>

<%= render 'form', submit_msg: 'Create Group' %>

<p>
  <%= link_to 'Cancel', groups_path %>
</p>

app/views/groups/show.html.erb
<h1>Show <%= @group.name %></h1>

<p>
  Group Name: <%= @group.name %>
</p>

<p>
  Has Access To:
  <table>
    <% @group.channels.each do |channel| %>
      <tr><td>
        <%= link_to channel.name, channel_path(channel) %>
      </td></tr>
    <% end %>
  </table>
</p>

<p>
  Members:
  <table>
    <% @group.users.each do |user| %>
      <tr><td>
        <%= user.name %>
      </td></tr>
    <% end %>
  </table>
</p>

<p>
  <%= link_to 'Edit Group', edit_group_path(@group) %>
</p>
<p>
  <%= link_to 'Group Index', groups_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChatApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<h1>New Message in <%= @channel.name %></h1>

<%= render 'shared/errors', container: @message %>

<%= form_for @message, url: new_message_path(@channel) do |f| %>
  <%= f.hidden_field :channel_id, value: @channel.id %>
  <p>
    <%= f.label 'User:' %>
    <%= f.collection_select :user_id, @channel.users, :id, :name %>
  </p>
  <p>
    <%= f.label 'Content:' %>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit 'Send Message' %>
  </p>
<% end %>

<p>
  <%= link_to 'Cancel', channel_path(@channel) %>
</p>

app/views/shared/_errors.html.erb
<div id='errors'>
  <ul style='list-style-type:none'>
    <% container.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
</div>

app/views/users/index.html.erb
<h1>Users Index</h1>

<table>
  <tr><%= link_to 'New User', new_user_path %></tr>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= user.name %>
      </td>
      <td>
        <%= link_to user.group.name, group_path(user.group) %>
      </td>
      <td>
        <%= link_to 'Delete',
            user_path(user),
            method: :delete,
            data: { confirm: 'Delete this User?' } %>
      </td>
    <tr>
  <% end %>
</table>

app/views/users/new.html.erb
<h1>Create a New User</h1>

<%= render 'shared/errors', container: @user %>

<%= form_for @user do |f| %>
  <p>
    <%= f.label 'Name:' %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label 'Group:' %>
    <%= f.collection_radio_buttons :group_id, Group.all, :id, :name %>
  </p>
  <p>
    <%= f.submit 'Create User' %>
  </p>
<% end %>

<p>
  <%= link_to 'Cancel', users_path %>
</p>